name: "LCOV Coverage Analyzer"
description: "Analyze LCOV coverage report and generate file list"
inputs:
  lcov-path:
    description: "LCOV 文件路径（必填）"
    required: true
  threshold:
    description: "覆盖率阈值（必填，百分比）"
    required: true
outputs:
  coverage-report:
    description: "覆盖率列表 JSON 数据"
runs:
  using: "node20"
  main: "dist/index.js"